In [1]:
from ipywidgets import Textarea
import io

if 'open' in globals():
    del open
if 'input' in globals():
    del input

original_open = open

class custom_open():
    def __init__(self):
        self.text = ''

    def __call__(self, file, *args, **kwargs):
        if file == 0:
            return io.StringIO(self.text)
        return original_open(file, *args, **kwargs)

    def updater(self, change):
        self.text = change["new"]

class custom_input():
    def __init__(self):
        self.__sio = io.StringIO('')
        self.shell = get_ipython()
        if self.shell.events.callbacks['pre_run_cell'] != []:
            self.shell.events.callbacks['pre_run_cell'] = []
        self.shell.events.register('pre_run_cell', self.pre_run_cell)

    def __call__(self):
        return self.__sio.readline().strip()

    def pre_run_cell(self, info):
        text = self.shell.user_ns.get('text_area', None).value
        self.__sio = io.StringIO(text)

open = custom_open()
input = custom_input()

text_area = Textarea()
text_area.observe(open.updater, names='value')
display(text_area)

Textarea(value='')

[11, 22, 32, 33, 14, 33, 14, 1]

In [13]:
from collections import defaultdict
from itertools import permutations
import numpy as np
#n=int(input())
#A=[int(i) for i in input().split()]
AA=[1,2,3,4,5,6,7]
for i in range(1,len(AA)+1):
    A=AA[0:i]
    aa = set(A)
    def f(A):
        idx=defaultdict(list)
        for i,a in enumerate(A):
            idx[a].append(i)
        return idx

    ida =f(A)

    #print(A)

    def calc(ida,idb,aa):
        dist = 0
        for i in aa:
            l1 = ida[i]
            l2 = idb[i]
            l1.sort()
            l2.sort()
            m1 = sum([abs(i-j) for i,j in zip(l1,l2[::-1])])
            m2 = sum([abs(i-j) for i,j in zip(l1[::-1],l2)])
            #print(i,max(m1,m2)*i)
            dist+=max(m1,m2)*i
        return dist

    ans = 0
    maxb = []
    for a in list(permutations(A)):
        #print(a)
        idb = f(list(a))
        c = calc(ida,idb,aa)
        if c > ans:
            maxb = a
            ans = c
    print(i,A,maxb,ans)

1 [1] [] 0
2 [1, 2] (2, 1) 3
3 [1, 2, 3] (3, 1, 2) 9
4 [1, 2, 3, 4] (4, 3, 1, 2) 21
5 [1, 2, 3, 4, 5] (5, 4, 1, 2, 3) 40
6 [1, 2, 3, 4, 5, 6] (6, 5, 4, 1, 2, 3) 67
7 [1, 2, 3, 4, 5, 6, 7] (7, 6, 5, 1, 2, 3, 4) 106


In [14]:
from collections import defaultdict
n=int(input())
A=[int(i) for i in input().split()]
#A=[1,10,2,4,3,9,5,7]
#A=[8,6,9,1,2,1]
peak=[]

keep = A[0]

def f(A):
    idx=defaultdict(list)
    for i,a in enumerate(A):
        idx[a].append(i)
    return idx
def calc(ida,idb,aa):
    dist = 0
    for i in aa:
        l1 = ida[i]
        l2 = idb[i]
        l1.sort()
        l2.sort()
        m1 = sum([abs(i-j) for i,j in zip(l1,l2[::-1])])
        m2 = sum([abs(i-j) for i,j in zip(l1[::-1],l2)])
        #print(i,max(m1,m2)*i)
        dist+=max(m1,m2)*i
    return dist

for i in range(1,len(A)):
    if keep>A[i]:
        l = A[:i-1]
        r = A[i-1:]
        l.sort()
        r.sort(reverse=True)
        #print(r,l)
        r.extend(l)
        peak.append(r)
        l = A[:i]
        r = A[i:]
        l.sort()
        r.sort(reverse=True)
        #print(r,l)
        r.extend(l)
        peak.append(r)
    keep = A[i]

if len(peak) == 0:
    if len(A)%2==0:
        yy = len(A)//2
        B=A[yy:][::-1]
        B.extend(A[:yy])
        ida =f(A)
        idb =f(B)
        #print(calc(ida,idb,aa))
        cal = calc(ida,idb,aa)
        print(cal)
    else:
        yy = len(A)//2 + 1
        B=A[yy:][::-1]
        B.extend(A[:yy])
        ida =f(A)
        idb =f(B)
        #print(calc(ida,idb,aa))
        cal = calc(ida,idb,aa)
        print(cal)
else:
    ans = 0
    for B in peak:
        aa = set(A)
        ida =f(A)
        idb =f(B)
        #print(calc(ida,idb,aa))
        cal = calc(ida,idb,aa)
        ans = max(ans,cal)
    print(ans)

40


In [10]:
B

[3, 4, 2, 1]

In [144]:
peak

[[10, 9, 7, 5, 4, 3, 2, 1],
 [9, 7, 5, 4, 3, 1, 2, 10],
 [9, 7, 5, 1, 2, 3, 4, 10]]

In [47]:
n,k=[int(i) for i in input().split()]
#dp=[0 for _ in range(k+2)]
#dp[k+1] = 1
def cmb(n, r, p):
    if (r < 0) or (n < r):
        return 0
    r = min(r, n - r)
    return fact[n] * factinv[r] * factinv[n-r] % p

p = 10 ** 9 + 7
N = 2*10 ** 5+1  # N は必要分だけ用意する
fact = [1, 1]
factinv = [1, 1]
inv = [0, 1]
 
for i in range(2, N + 1):
    fact.append((fact[-1] * i) % p)
    inv.append((-inv[p % i] * (p // i)) % p)
    factinv.append((factinv[-1] * inv[-1]) % p)


ans=0
for i in range(k,n+2):
    ans = (ans+ cmb(n, i, p))%p
    print(i,cmb(n,2,p))
print(ans)

2 3
3 3
4 3
4


In [17]:
n,q=[int(i) for i in input().split()]
edge=[[] for _ in range(n)]
for _ in range(n-1):
    a,b = [int(i) for i in input().split()]
    edge[a-1].append(b-1)
    if edge[b-1] != []:
        edge[a-1].extend(edge[b-1])
    else:
        pass
        
    edge[b-1].append(a-1)
    if edge[a-1] != []:
        edge[b-1].extend(edge[a-1])
    else:
        pass

In [18]:
edge

[[1], [0, 1, 2, 3], [1, 0, 1, 2], [1, 0, 1, 2, 3]]

In [7]:
import numpy as np

H,W = map(int,input().split())
temp = np.array([list(input()) for _ in range(H)])
# 周りに壁を、0,1化
map = np.zeros((H+2,W+2),dtype=np.int32)
map[1:-1,1:-1][temp == '.'] = 1

# x軸正方向の集計
def F():
  x = map.copy()
  for row in range(1,H+1):
    zero_idx = np.nonzero(x[row]==0)[0]
    x[row, zero_idx[1:]] = 1-np.diff(zero_idx) # cumsumで求められるように変形
  x = x.cumsum(axis = 1)
  return x

# y軸
def G():
  x = map.T.copy()
  for row in range(1,W+1):
    zero_idx = np.nonzero(x[row]==0)[0]
    x[row, zero_idx[1:]] = 1-np.diff(zero_idx) # cumsumで求められるように変形
  x = x.cumsum(axis = 1)
  return x.T

answer = np.zeros_like(map)
# x軸
answer += F()
# 逆順
map = map[:,::-1]
answer += F()[:,::-1]
map = map[:,::-1]

# y軸
answer += G()
# 逆順
map = map[::-1,:]
answer += G()[::-1,:]

answer = np.max(answer) - 3
print(answer)

8


In [355]:
M

[[-3, 5, 4, -3, 3, 2],
 [6, 8, 7, 7, 6, -3],
 [5, 7, 6, 6, -3, 2],
 [-3, 4, -3, 5, 3, 4]]

In [346]:
AA+BB

[[0, 1, 1, 0, 1, 1],
 [1, 2, 2, 1, 2, 0],
 [2, 3, 3, 2, 0, 1],
 [0, 4, 0, 3, 1, 2],
 [0, 2, 1, 0, 2, 1],
 [5, 4, 3, 2, 1, 0],
 [4, 3, 2, 1, 0, 1],
 [0, 1, 0, 3, 2, 1]]

In [342]:
BB

[[0, 2, 1, 0, 2, 1],
 [5, 4, 3, 2, 1, 0],
 [4, 3, 2, 1, 0, 1],
 [0, 1, 0, 3, 2, 1]]

In [343]:
CC

[[0, 4, 3, 0, 2, 1],
 [2, 3, 2, 3, 1, 0],
 [1, 2, 1, 2, 0, 2],
 [0, 1, 0, 1, 1, 1]]

In [339]:
B

[[True, True, True, False, True, False],
 [True, False, True, True, True, True],
 [False, True, True, True, True, True],
 [True, True, False, True, True, False]]

In [340]:
C

[[False, True, True, False],
 [True, True, True, True],
 [False, True, True, True],
 [True, True, True, False],
 [True, False, True, True],
 [True, True, False, True]]

In [304]:
convert(L)

[[0, 1, 2, 0, 1, 2],
 [1, 2, 3, 4, 5, 0],
 [1, 2, 3, 4, 0, 1],
 [0, 1, 0, 1, 2, 3]]

In [309]:
mir(convert(mir(L)))

[[0, 2, 1, 0, 2, 1],
 [5, 4, 3, 2, 1, 0],
 [4, 3, 2, 1, 0, 1],
 [0, 1, 0, 3, 2, 1]]

In [286]:
import numpy as np
 
def convert(L):
    dp = np.zeros((L.shape[0],L.shape[1]), dtype='int')
    for i in range(L.shape[0]):
        l=L[i]
        for j in range(L.shape[1]):
            if l[j]:
                if j == 0:
                    dp[i][j] = 1
                else:
                    dp[i][j] = dp[i][j-1] + 1
            else:
                dp[i][j] = 0
    return dp
H,W=map(int,input().split())
L= np.zeros((H,W),dtype='bool')
for i in range(H):
    L[i]=list(map(lambda x: False if x=="#" else True,list(input()) ))
 
ans = convert(L) + np.fliplr(convert(np.fliplr(L))) + convert(L.T).T + np.flipud(convert(np.flipud(L).T).T) - 3
print(np.max(ans))


8


In [288]:
np.fliplr(convert(np.fliplr(L))) 

array([[0, 2, 1, 0, 2, 1],
       [5, 4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0, 1],
       [0, 1, 0, 3, 2, 1]])

In [302]:
[list(l[::-1]) for l in L]

[[True, True, False, True, True, False],
 [False, True, True, True, True, True],
 [True, False, True, True, True, True],
 [True, True, True, False, True, False]]

In [300]:
L[::-1]

array([[False,  True, False,  True,  True,  True],
       [ True,  True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True, False],
       [False,  True,  True, False,  True,  True]])

In [297]:
convert(L[::-1])[::-1]

array([[0, 1, 2, 0, 1, 2],
       [1, 2, 3, 4, 5, 0],
       [1, 2, 3, 4, 0, 1],
       [0, 1, 0, 1, 2, 3]])

In [290]:
convert(L)

array([[0, 1, 2, 0, 1, 2],
       [1, 2, 3, 4, 5, 0],
       [1, 2, 3, 4, 0, 1],
       [0, 1, 0, 1, 2, 3]])

In [269]:
L

[[False, True, True, False, True, True],
 [True, True, True, True, True, False],
 [True, True, True, True, False, True],
 [False, True, False, True, True, True]]

In [265]:
K

[[False, True, True, False],
 [False, True, True, False],
 [False, True, True, False],
 [False, True, True, False],
 [False, True, True, False],
 [False, True, True, False]]

In [259]:
L

[[False, True, True, False, True, True],
 [True, True, True, True, True, False],
 [True, True, True, True, False, True],
 [False, True, False, True, True, True]]

In [203]:
from library import UnionFind

N=int(input())
K=[]
for _ in range(N-1):
    K.append(list(map(int,input().split())))
tree = UnionFind(N)
for u,v,w in K:
    if w%2==0:
        tree.union(u-1,v-1)

In [205]:
# N: 頂点数
# G[v]: 頂点vの子頂点 (親頂点は含まない)
#
# - construct
# prv[u] = v: 頂点uの一つ上の祖先頂点v
# - lca
# kprv[k][u] = v: 頂点uの2^k個上の祖先頂点v
# depth[u]: 頂点uの深さ (根頂点は0)

LV = (N-1).bit_length()
def construct(prv):
    kprv = [prv]
    S = prv
    for k in range(LV):
        T = [0]*N
        for i in range(N):
            if S[i] is None:
                continue
            T[i] = S[S[i]]
        kprv.append(T)
        S = T
    return kprv

def lca(u, v, kprv, depth):
    dd = depth[v] - depth[u]
    if dd < 0:
        u, v = v, u
        dd = -dd

    # assert depth[u] <= depth[v]
    for k in range(LV+1):
        if dd & 1:
            v = kprv[k][v]
        dd >>= 1

    # assert depth[u] == depth[v]
    if u == v:
        return u

    for k in range(LV-1, -1, -1):
        pu = kprv[k][u]; pv = kprv[k][v]
        if pu != pv:
            u = pu; v = pv

    # assert kprv[0][u] == kprv[0][v]
    return kprv[0][u]

In [206]:
import random as r

namelist=['apple','grape','orange','lemon','banana']

class node:
    def __init__(self, name, children):
        self.name = name  # String
        self.children = children  # List of Class node

    def display(self, indent = 0):
        if self.children != None:
            print(' '*indent)+self.name
            for c in self.children:
                c.display(indent+1)
        else:
            print(' '*indent)+self.name

        

def maketree(maxdepth):
    if (maxdepth > 0):
        children = [ maketree(maxdepth-1) for i in range(2) ]
    else:
        children = None

    rootnode = node(r.choice(namelist),children)
    return rootnode

In [225]:
N=int(input())
edge = [[] for _ in range(N+1)]

for _ in range(N-1):
    u,v,w=[int(x) for x in input().split()]
    if w&1:
        edge[u].append((v,-1))
        edge[v].append((u,-1))
    else:
        edge[u].append((v,1))
        edge[v].append((u,1))
    
color = [None]*(N+1)

def set_color(v,c):
    color[v]=c
    for x,sgn in edge[v]:
        if color[x] is None:
            set_color(x,sgn*c)
set_color(1,1)

for x in color[1:]:
    print((x+1)//2)

1
1
1
1
1


In [223]:
3&1

1

In [ ]:
color = [-1 for _ in range(N)]
for u,v,w in K:
    if w%2==0:
        color[u-1]

In [27]:
orders = [["David","3","Ceviche"],["Corina","10","Beef Burrito"],["David","3","Fried Chicken"],["Carla","5","Water"],["Carla","5","Ceviche"],["Rous","3","Ceviche"]]

In [28]:
for _, n, f in orders:
    print(n,f)

3 Ceviche
10 Beef Burrito
3 Fried Chicken
5 Water
5 Ceviche
3 Ceviche


In [102]:
n,m,k=2,3,1

In [103]:
def maxi(l):
    mv=-1
    mi=-1
    sc=0
    n=len(l)
    for i in range(n):
        if mv<l[i]:
            mv=l[i]
            mi=i
            sc+=1
    return l,mv,mi,sc

In [104]:
maxi([4,6,2,8,4,6])

([4, 6, 2, 8, 4, 6], 8, 3, 3)

In [82]:
fs = [0 for _ in range(len(T))]

In [ ]:
for t in T:
    if t 

In [71]:
[["Table","Beef Burrito","Ceviche","Fried Chicken","Water"],["3","0","2","1","0"],["5","0","1","0","1"],["10","1","0","0","0"]]

[['Table', 'Beef Burrito', 'Ceviche', 'Fried Chicken', 'Water'],
 [3, 0, 2, 1, 0],
 [5, 0, 1, 0, 1],
 [10, 1, 0, 0, 0]]

In [193]:
N = 50
M = 100
K = 25
lim = 10**9+7
dp = [[[0 for _ in range(N+2)] for _ in range(M+2)] for _ in range(N+2)]
for i in range(1,M+1):
    dp[0][i][1] = 1

for n in range(1,N):
    for max_ in range(1,M+1):
        for k in range(1,K+1):
            for l in range(1,max_):
                dp[n][max_][k] += dp[n-1][l][k-1]
                dp[n][max_][k] += dp[n-1][max_][k]*max_
                dp[n][max_][k] %= lim
print(sum([dp[N-1][i][K] for i in range(M+1)]))

39174129192


In [189]:
[dp[N-1][i][K] for i in range(M+1)]

[0, 0, 2, 6]

In [190]:
dp

[[[0, 0, 0, 0], [0, 1, 0, 0], [0, 1, 0, 0], [0, 1, 0, 0], [0, 0, 0, 0]],
 [[0, 0, 0, 0], [0, 0, 0, 0], [0, 2, 0, 0], [0, 6, 0, 0], [0, 0, 0, 0]],
 [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]],
 [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]]

In [152]:
i:n
j:max_
l:k
ii:l

[[[1, 1, 1], [0, 0, 0], [0, 0, 0]], [[1, 2, 3], [0, 1, 2], [0, 0, 0]]]

In [ ]:
n,

In [75]:
def f(s):
    if s[-1]=="a":
        return [s+"b",s+"c"]
    elif s[-1]=="b":
        return [s+"a",s+"c"]
    else:
        return [s+"a",s+"b"]

In [89]:
def g(n):
    k=["a","b","c"]
    if n==1:
        return k
    else:
        h=g(n-1)
        ans=[]
        for l in h:
            for j in k:
                if l[-1] != j:
                    ans.append(l+j)
        return ans

In [91]:
ans = g(3)

In [117]:
def fib_memo(n):
    memo=["EMPTY"]*(n+1)
    def _fib(n):
        if n == 1:
            return 0
        elif n == 2:
            return 1
        elif memo[n] != "EMPTY":
            return memo[n]
        else:
            memo[n] = _fib(n-1)+_fib(n-2)
            return memo[n]
    return _fib(n)

In [125]:
def func(n):
    fibonacci = [1,1]
    for i in range(2,n):
        fibonacci.append(fibonacci[i-2]+fibonacci[i-1])
    return fibonacci

In [127]:
fs =func(50)

In [231]:
from collections import defaultdict
s = "600342244431311113256628376226052681059918526204"
k = 703
lim = 10**9+7
dp = [[0,0] for _ in range(len(s))]
for i,t in enumerate(s):
    if i == 0:
        dp[i][0]=1
        dp[i][1]={t:1}
    else:
        l=defaultdict(int)
        for z,m in dp[i-1][1].items():
            if ((int(z+t)<=k) and (int(z+t)>0)):
                l[z+t] +=m
                #l.append(z+t)
        if t != "0":
            l[t] += dp[i-1][0]
            #l.extend([t]*dp[i-1][0])
        dp[i][0] = sum(l.values()) % lim
        dp[i][1] = l
print(dp[-1][0])

411743991


In [256]:
eval("0o1+1")

2

In [251]:
class Solution:
    def isNumber(self, s: str) -> bool:
        if s == "e" or s == " ":
            return False
        else:
            try:
                print(eval("%s+1" % s))
                return True
            except:
                return False

In [252]:
a=Solution()

In [254]:
a.isNumber("01")

False

In [213]:
from collections import defaultdict
s = "1234567890"
k = 90

dp = [[0,[]] for _ in range(len(s))]
for i,t in enumerate(s):
    if i == 0:
        dp[i][0]=1
        dp[i][1].append(t)
    else:
        l=[]
        for z in dp[i-1][1]:
            if ((int(z+t)<=k) and (int(z+t)>0)):
                l.append(z+t)
        if t != "0":
            l.extend([t]*dp[i-1][0])
        dp[i][0] = len(l)
        dp[i][1] = l
print(dp[-1][0])

34


In [214]:
dp

[[1, ['1']],
 [2, ['12', '2']],
 [3, ['23', '3', '3']],
 [5, ['34', '34', '4', '4', '4']],
 [8, ['45', '45', '45', '5', '5', '5', '5', '5']],
 [13, ['56', '56', '56', '56', '56', '6', '6', '6', '6', '6', '6', '6', '6']],
 [21,
  ['67',
   '67',
   '67',
   '67',
   '67',
   '67',
   '67',
   '67',
   '7',
   '7',
   '7',
   '7',
   '7',
   '7',
   '7',
   '7',
   '7',
   '7',
   '7',
   '7',
   '7']],
 [34,
  ['78',
   '78',
   '78',
   '78',
   '78',
   '78',
   '78',
   '78',
   '78',
   '78',
   '78',
   '78',
   '78',
   '8',
   '8',
   '8',
   '8',
   '8',
   '8',
   '8',
   '8',
   '8',
   '8',
   '8',
   '8',
   '8',
   '8',
   '8',
   '8',
   '8',
   '8',
   '8',
   '8',
   '8']],
 [55,
  ['89',
   '89',
   '89',
   '89',
   '89',
   '89',
   '89',
   '89',
   '89',
   '89',
   '89',
   '89',
   '89',
   '89',
   '89',
   '89',
   '89',
   '89',
   '89',
   '89',
   '89',
   '9',
   '9',
   '9',
   '9',
   '9',
   '9',
   '9',
   '9',
   '9',
   '9',
   '9',
   '9',
   '9',
   

In [132]:
k=7
ans = []
for f in fs[::-1]:
    if f<=k:
        ans.append(f)
        k -= f
print(len(ans))

2


In [95]:
for i in range(100):
    if Fib(i) > 10**9:
        print(i,Fib(i))
        break

RecursionError: maximum recursion depth exceeded

In [77]:
for i in ["a","b","c"]:
    print(f("bab"+i))

['babab', 'babac']
['babba', 'babbc']
['babca', 'babcb']


In [46]:
def f(n,s):
    if n==0:
        return ["a","b","c"]
    else:
        return ["a",s+"b",s+"c"]

3 0 0
[ 1 0
a 1 0
b 1 0
c 1 0
] 1 0
3[abc]

6 6
y 0 0
t 0 0
h 0 0
t 0 0
n 0 0
f 0 0
4 0 0
[ 1 0
a 1 0
b 1 0
] 1 0
ythtnf4[ab]


KeyboardInterrupt: 

In [55]:
list(decomp("s"))

KeyboardInterrupt: 

In [51]:
#!/usr/bin/env python
import sys
def decomp(text, start=0, times=1):
    # Repeat iteration over our sub-chunk N times.
    for _ in range(times):
        i = start
        # Until we hit the end of the string, or end of our chunk...
        while i < len(text) and text[i] != ']':
            # Emit letters as themselves.
            if text[i].islower():
                yield text[i]
        # If it's not a letter, it must be digit(s).  Convert to integer.
        else:
            sub_times = 0
            while text[i].isdigit():
                sub_times = sub_times * 10 + int(text[i])
                i += 1
            i += 1  # Skip past open-bracket
            # Start an iterator over the sub-chunk.
            for item in decomp(text, i, sub_times):
                if isinstance(item, basestring):
                    yield item
                else:
                    i = item
            i += 1
    if start > 0:
        yield i
def decompress(text):
    for letter in decomp(text):
        sys.stdout.write(letter)
    sys.stdout.write('')



In [56]:
import heapq

In [57]:
stones =[5,4,7,2,1,2]
stones = [-i for i in stones]
l = heapq.heapify(stones)
n = len(stones)
while n > 1:
    a = heapq.heappop(l)
    b = heapq.heappop(l)
    if a == b:
        n -=2
    else:
        heapq.heappush(l,-abs(a-b))
        n -= 1
if n == 0:
    return 0
else:
    return -heapq.heappop(l)

TypeError: heap argument must be a list

In [61]:
heapq.heapify([5,3])

In [66]:
from itertools import accumulate

In [68]:
accumulate([3,5,])